### ISSUE TITLE
0xrice.cooker - Rounding up when bidding without protection lead to bidder have to spend more to buy borrower's collateral than expected

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-arcadia-judging#10]
0xrice.cooker

medium

# Rounding up when bidding without protection lead to bidder have to spend more to buy borrower's collateral than expected

## Summary
Rounding up when bidding without protection lead to bidder have to spend more to buy borrower's collateral than expected
## Vulnerability Detail
There's 2 rounding issue need to solve in Liquidator contract. 
First of all, total share of any liquidation can be bigger than 10000 and up to 10015
```solidity
    function _getAssetShares(AssetValueAndRiskFactors[] memory assetValues)
        internal
        pure
        returns (uint32[] memory assetShares)
    {
        uint256 length = assetValues.length;
        uint256 totalValue;
        for (uint256 i; i < length; ++i) {
            unchecked {
                totalValue += assetValues[i].assetValue;
            }
        }
        assetShares = new uint32[](length);
        
        if (totalValue == 0) return assetShares;
        
        for (uint256 i; i < length; ++i) {
            assetShares[i] = uint32(assetValues[i].assetValue.mulDivUp(ONE_4, totalValue));//<@@ all rounding up -> total asset share will bigger than 10000
        }
    }
```

Secondly, rounding assetShares of any collateral will always be lower than 10000, rounding up here can make bidder have to spend more money for bidding
```solidity
    function _calculateTotalShare(AuctionInformation storage auctionInformation_, uint256[] memory askedAssetAmounts)
        internal
        view
        returns (uint256 totalShare)
    {
        uint256[] memory assetAmounts = auctionInformation_.assetAmounts;
        uint32[] memory assetShares = auctionInformation_.assetShares;
        if (assetAmounts.length != askedAssetAmounts.length) {
            revert LiquidatorErrors.InvalidBid();
        }

        for (uint256 i; i < askedAssetAmounts.length; ++i) {
            unchecked {
                totalShare += askedAssetAmounts[i].mulDivUp(assetShares[i], assetAmounts[i]);//<@@ because the assetShares[i] < 10000 -> lead to to rounding issue
            }
        }
    }
```

Let have a scenario:	
	- Let say there's borrower who get liquidated and have collaterals worth 100k
	- Let say there's one asset in the bundle that is 1e18 amount with value is 1001$ -> 101 share
	- Bidder want to buy 0.1e18 amount of that asset which is only 10.1 share, but in reality user must pay 11 share because of round up system
	- Let say the bid price of that asset still 1001$/1e18 token. Bidder must pay 110.11$ for 0.1e18 that valued 100.1$ -> losing 10.01$

Note that borrower can have up to 15 type of collateral. If bidder scatter askAssetAmounts across multiple asset, losing cost because of rounding can be massive

Moreover, the total share of a action will not be likely be 10000. It will be in the range [10000, 10015], depend on the amount of asset type in the account. The reason is that due to volatile of the value of the asset, there's super low chance that `assetValues[i].assetValue * ONE_4 % totalValue == 0`, hence rounding up will happen and the total share will surpass 10000

## Impact
Impact 1: Bidder have no protection about the outcome of the result, hence is vurnable to losing when bidding. 
Impact 2: Bidder on average will have to pay [0.01% - 0.15%] more. As the consequence, bidder will need to wait longer to have a desirable price to buy than expected

## Code Snippet
https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/Liquidator.sol#L33

https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/Liquidator.sol#L266

https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/Liquidator.sol#L340
## Tool used 
Manual Review
## Recommendation
Some potential fix:
- Change `ONE_4` const in Liquidator contract from 1e4 to 1e18 to avoid rounding up
- Have an input to check maxAssetWillPay in Liquidator.bid()
- Make bidder buy in `askedAssetShares` instead of `askedAssetAmounts`

**Comment by tnquanghuy0512** [comment]
Escalate

The price of assets can't be set by the bidder, since we will not know when the transaction will be executed or wait in queue.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The price of assets can't be set by the bidder, since we will not know when the transaction will be executed or wait in queue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Thomas-Smets** [comment]
You do know the current price.
And that price will only decrease over time, so the bidder knows it will round up and can up front calculate the Maximum price he will pay.

**Comment by tnquanghuy0512** [comment]
How can you know the price when the transaction happen? If you pay sufficient normal gas for transaction, there's can still be a chance that the transaction will get delay when the chain getting lots of transactions pushing with higher gas

**Comment by Thomas-Smets** [comment]
You know the current price, the auction price curve is a strictly decreasing function.
If your transaction is delayed, the actual price can only be lower than the price you calculated.

**Comment by nevillehuang** [comment]
Agree with sponsors comments, the protocol operates a dutch auction, so users should be responsible in determining the maximum price they are willing to pay based on current auction price, so this would constitute user input error. Conversely if you round down, you can also argue the other way where the bid amount could be lower than intended.

At that point of time where bidder executes his bid, he would have already accepted that he is willing to pay that amount to bid, so worse case scenario the surplus used to bid is sent to the account owner as seen [here](https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/LendingPool.sol#L501-L508), which is intended.

**Comment by Czar102** [comment]
It seems this issue has been correctly judged. Planning to reject the escalation and leave the issue as is.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [tnquanghuy0512](https://github.com/sherlock-audit/2023-12-arcadia-judging/issues/10/#issuecomment-1970643525): rejected
