### ISSUE TITLE
0xrice.cooker - Uphappy flow when liquidation not check if the debt owner have any unwithdraw surplus amount stored in the Lending Pool

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-arcadia-judging#12]
0xrice.cooker

medium

# Uphappy flow when liquidation not check if the debt owner have any unwithdraw surplus amount stored in the Lending Pool

## Summary
Uphappy flow when liquidation not check if the debt owner's `realisedLiquidityOf[debt's owner]` stored in the Lending Pool. Instead it will decrease staker's vault to payback the debt

## Vulnerability Detail
The variable `mapping(address => uint256) internal realisedLiquidityOf` used to distribute mostly to LendingPool's tranches and treasury. It also ditribute to normal users in these case
	- Reward to initator who startLiquidation()
	- Reward to terminator who is the settle the auction
	- Send surplus amount to the debt owner when terminator overbid in happy flow

After that, normal user can withdraw the asset out using withdrawFromLendingPool().

Note the surplus amount received by debt owner can't be used to deduct the amount of the new debt when that debt owner got liquidated again. When things go wrong, the new debt have go to unhappy flow and have to decrease tranche liquidity to pay back bad debt. Because of that, staker in the junior tranche will lose their profits. 
We can deduct the impact of bad debt here by checking if the debt owner's `realisedLiquidityOf[debt owner]` have any unclaimed assets to pay back the debt.

## Impact
This lead to the protocol staking vault more vurnable to bad debt

## Code Snippet
https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/LendingPool.sol#L938C1-L966C6
https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/LendingPool.sol#L372C1-L385C6
https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/LendingPool.sol#L983C1-L1031C6
## Tool used 
Manual Review
## Recommendation
Step 1: we need to send surplus amount when happy flow to the debt account, not debt owner -> easier for step 2, 3
Step 2: we need to restrict all borrower who have borrow any asset in the LendingPool by DOS withdrawFromLendingPool(). We must only let borrower withdraw when borrower have no debt any that particular LendingPool
Step 3: we need to implement the logic of deducting logic in `_settleLiquidationHappyFlow()` function

Here is my fix, note that this is not tested and not bug-free:
Step 1: https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/LendingPool.sol#L938C1-L966C6

```diff
    function _settleLiquidationHappyFlow(
        address account,
        uint256 startDebt,
        uint256 minimumMargin_,
        address terminator,
        uint256 surplus
    ) internal {
        (uint256 initiationReward, uint256 terminationReward, uint256 liquidationPenalty) =
            _calculateRewards(startDebt, minimumMargin_);

        _syncLiquidationFee(liquidationPenalty);

        totalRealisedLiquidity =
            SafeCastLib.safeCastTo128(totalRealisedLiquidity + terminationReward + liquidationPenalty + surplus);

        unchecked {
-           if (surplus > 0) realisedLiquidityOf[IAccount(account).owner()] += surplus;
+           if (surplus > 0) realisedLiquidityOf[account] += surplus;
            realisedLiquidityOf[terminator] += terminationReward;
        }

        _endLiquidation();
    }

```

Step 2: https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/LendingPool.sol#L372C1-L385C6
```diff
-   function withdrawFromLendingPool(uint256 assets, address receiver)
+   function withdrawFromLendingPool(uint256 assets, address receiver, address account)
        external
        whenWithdrawNotPaused
        processInterests
    {
    	address withdrawer = msg.sender;
+	if (account != address(0)){
+		if(IFactory(ACCOUNT_FACTORY).ownerOfAccount(account) != msg.sender || maxWithdraw(account) > 0) revert;
+		withdrawer = account;
+	}
    

-       if (realisedLiquidityOf[msg.sender] < assets) revert LendingPoolErrors.AmountExceedsBalance();
+       if (realisedLiquidityOf[withdrawer] < assets) revert LendingPoolErrors.AmountExceedsBalance();
        unchecked {
-           realisedLiquidityOf[msg.sender] -= assets;
+           realisedLiquidityOf[withdrawer] -= assets;
            totalRealisedLiquidity = SafeCastLib.safeCastTo128(totalRealisedLiquidity - assets);
        }

        asset.safeTransfer(receiver, assets);
    }
```

Step 3: https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/LendingPool.sol#L983C1-L1031C6
```diff
    function settleLiquidationUnhappyFlow(
        address account,
        uint256 startDebt,
        uint256 minimumMargin_,
        address terminator
    ) external whenLiquidationNotPaused onlyLiquidator processInterests {
        (uint256 initiationReward, uint256 terminationReward, uint256 liquidationPenalty) =
            _calculateRewards(startDebt, minimumMargin_);


        uint256 debtShares = balanceOf[account];
        uint256 openDebt = convertToAssets(debtShares);
        uint256 badDebt;
        if (openDebt > terminationReward + liquidationPenalty) {
            unchecked {
                badDebt = openDebt - terminationReward - liquidationPenalty;
            }
            
+           uint256 deductFromBorrower = realisedLiquidityOf[account];
+           if (badDebt > deductFromBorrower){
+		totalRealisedLiquidity = uint128(totalRealisedLiquidity - badDebt);
+            	badDebt -= deductFromBorrower;
+		realisedLiquidityOf[account] = 0;
+		_processDefault(badDebt);
+           } else {
+		totalRealisedLiquidity = uint128(totalRealisedLiquidity - badDebt);
+	     	realisedLiquidityOf[account] -= badDebt;
+	     	badDebt = 0;
+	    }

-            totalRealisedLiquidity = uint128(totalRealisedLiquidity - badDebt);
-            _processDefault(badDebt);
        } else {
            ...
        }

        ...
    }

```

**Comment by tnquanghuy0512** [comment]
Escalate

Can I have a better explanation? This fix will protect the protocol when bad debt!

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Can I have a better explanation? This fix will protect the protocol when bad debt!  

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Sponsors comments

> This is as intended. Users can indeed have some surplus left in the liquidity pool from previous liquidations, however we opt not to use such funds. It would create an unfair situation where a user leaves the surplus (doesn’t get interest, but aids the liquidity pool), who then gets liquidated and has to pay the baddebt themselves, vs a user that had a surplus, withdraws it, and now their baddebt gets paid by the LPs. Next to that, it would introduce additional logic and complexity, and junior tranche LPs would have a skewed risk-reward for some of the debtors.

**Comment by tnquanghuy0512** [comment]
@nevillehuang 

The situation is NOT unfair in my fix, my fix will lock the borrower's surplus when there's still debt inside. Only when user pay back all the debt then the surplus will be unlock for borrower to withdraw. Because of that, borrower will be more incentive to pay back all so that they can earn the surplus amount, plus the tranche will be less vulnerable when there's bad debt happen. It's a win-win situation.

**Comment by Thomas-Smets** [comment]
Yes it is unfair, as we explained before:

> It would create an unfair situation where a user leaves the surplus (doesn’t get interest, but aids the liquidity pool), who then gets liquidated and has to pay the baddebt themselves, vs a user that had a surplus, withdraws it, and now their baddebt gets paid by the LPs.

**Comment by tnquanghuy0512** [comment]
@Thomas-Smets 
Let's breaking down this:
>It would create an unfair situation where a user leaves the surplus (doesn’t get interest, but aids the liquidity pool), who then gets liquidated and has to pay the baddebt themselves, vs a user that had a surplus, withdraws it, and now their baddebt gets paid by the LPs.

In here you compare the situations when the borrower withdraw the surplus VS borrower NOT withdraw the surplus. But in this case, with my fix, we will LOCK the surplus of the borrower, which make they can NOT withdraw it until the borrower pay back all the debt. Because of that, your unfair situation that you explained doesn't exist. 
Not only that my fix is fair, it will make the borrower more incentive to pay all of the debt back, since they can unlock the surplus amount after they pay all the debt. Moreover, the protocol is more protective in this way when there's bad debt happens

In summary, it will have 2 benefit: 
- Protect protocol when bad debt happen
- More incentive for borrower to pay back the debt

I don't see why this issue should not be fix

**Comment by Thomas-Smets** [comment]
Providing liquidity, or having done actions as liquidator (-> the liquidityOf() balance in the LendingPool is greater than 0).
Is independent from any actions that users does as borrower.

Debt is covered by the assets in the Account.
We will not additionally punish borrowers who are already liquidated, by also slashing their assets in other places.

With your logic, we could also check if the borrower has non-zero approvals, and if so withdraw remaining assets from their wallet via a transferFrom.

**Comment by j-vp** [comment]
> But in this case, with my fix, we will LOCK the surplus of the borrower, which make they can NOT withdraw it until the borrower pay back all the debt.

Also note that this is not correct: when there is a surplus, it means all debt (including all penalties) has already been repaid and that as such there is a surplus. At that moment in time, it wouldn't make sense to (b)lock it, simply because it may be used in a potential future liquidation that causes bad debt due to that user. In other words, we would never be able to unlock the surplus of a user.

**Comment by Czar102** [comment]
This is not an issue, but a new functionality proposal. Planning to reject the escalation and leave the issue as is.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [tnquanghuy0512](https://github.com/sherlock-audit/2023-12-arcadia-judging/issues/12/#issuecomment-1970657597): rejected
