### ISSUE TITLE
0x52 - The permissionless variant of `LendingPoolGuardian#unpause` will cause race conditions between repayment and liquidation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-arcadia-judging#146]
0x52

medium

# The permissionless variant of `LendingPoolGuardian#unpause` will cause race conditions between repayment and liquidation

## Summary

When the permissionless variant of `LendingPoolGuardian#unpause` is called it will simultaneously unlock repayment and liquidation. While repayment is blocked, users who are underwater cannot repay their position ahead of time. This creates race conditions when called that will lead to large numbers of users being unfairly liquidated as they were given no time to repay.

## Vulnerability Detail

[LendingPoolGuardian.sol#L148-L152](https://github.com/sherlock-audit/2023-12-arcadia/blob/main/lending-v2/src/guardians/LendingPoolGuardian.sol#L148-L152)

    function unpause() external override afterCoolDownOf(30 days) {
        emit PauseFlagsUpdated(
            repayPaused = false, withdrawPaused = false, borrowPaused, depositPaused, liquidationPaused = false
        );
    }

As shown above, withdrawals and liquidations are unlocked at the same time, those who have been blocked from repaying will now have to race to repay their loan before they are queued for liquidation. While it is true that users can still repay even during the liquidation process, the liquidation fees are applied immediately causing the user to pay back excess debt.

## Impact

Race conditions after unpausing will cause users to pay unfair fees best case and worst case they will be unfairly liquidated.

## Code Snippet

[LendingPoolGuardian.sol#L148-L152](https://github.com/sherlock-audit/2023-12-arcadia/blob/main/lending-v2/src/guardians/LendingPoolGuardian.sol#L148-L152)

## Tool used

Manual Review

## Recommendation

There should be a grace timer after liquidation have been resumed so that no users can be liquidate for some amount of time after they resume.

**Comment by IAm0x52** [comment]
Escalate

Creating this escalation to address the lead judge's comment above.

I want to reiterate that I am specifically referring to the permissionless version of [unpause](https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/guardians/LendingPoolGuardian.sol#L148-L152). This one can be called by anyone after the protocol has been paused for longer 30 days and operates under the assumption that admin is not involved (absent, malicious, etc.). 

I would also like to clarify that this is not front-running but race conditions which doesn't rely on knowledge of the other user's transaction. All information is public. One user is trying to repay while the other is trying to liquidate them. 

Lastly even though the assets go to auction and the user will receive excess funds from the sale they will still be forced to unfairly pay a liquidation fee so there is tangible loss to the user.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Creating this escalation to address the lead judge's comment above.
> 
> I want to reiterate that I am specifically referring to the permissionless version of [unpause](https://github.com/sherlock-audit/2023-12-arcadia/blob/de7289bebb3729505a2462aa044b3960d8926d78/lending-v2/src/guardians/LendingPoolGuardian.sol#L148-L152). This one can be called by anyone after the protocol has been paused for longer 30 days and operates under the assumption that admin is not involved (absent, malicious, etc.). 
> 
> I would also like to clarify that this is not front-running but race conditions which doesn't rely on knowledge of the other user's transaction. All information is public. One user is trying to repay while the other is trying to liquidate them. 
> 
> Lastly even though the assets go to auction and the user will receive excess funds from the sale they will still be forced to unfairly pay a liquidation fee so there is tangible loss to the user.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
I believe the root cause still stems from the admin (guardian) pausing repayments and liquidations that resulted in the above mentioned issue, so the following rule applies. 

CC: @Thomas-Smets @j-vp @Czar102 

> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds

**Comment by Thomas-Smets** [comment]
The permissionless variant is like a last resort thing users have if the protocol owners turn malicious (or all die while the pause guardian could still pause the protocol) and lock up funds.

Under all circumstances of normal operation the onlyOwner variant is used.

The permissionless variant is like a emergency case of an emergency case, I would like to keep it as simple as possible.

**Comment by Czar102** [comment]
Fully agree with https://github.com/sherlock-audit/2023-12-arcadia-judging/issues/146#issuecomment-1970573326, planning to reject the escalation and leave the issue as is.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IAm0x52](https://github.com/sherlock-audit/2023-12-arcadia-judging/issues/146/#issuecomment-1969378644): rejected
