### ISSUE TITLE
xtazy888 - If there's dust amount left within a tranche, it might cause next depositor to lose their money

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-arcadia-judging#66]
xtazy888

high

# If there's dust amount left within a tranche, it might cause next depositor to lose their money

## Summary
If there's dust amount left within a tranche, it might cause next depositor to lose their money

## Vulnerability Detail
Whenever there's bad debt created, it reduces the share value of the most junior tranche. In certain cases, it may just happen that all shares are worth only a dust amount. (e.g. 1e18 shares are worth a total of 10 wei)

```solidity
   function convertToSharesAndSync(uint256 assets) public returns (uint256 shares) {
        // Cache totalSupply.
        uint256 supply = totalSupply;

        shares = supply == 0 ? assets : assets.mulDivDown(supply + VAS, totalAssetsAndSync() + VAS);
    }
```
However, when calculating the shares to be minted, there's virtual reserves to be accounted for. They are usually used to prevent from inflation attacks, but in this case, they would cause us another error. For reference we will use usual values for a token with 18 decimals - 1000 VAS

The actual share/asset ratio should be `1e18` : 10, but because of the virtual reserves, the newly minted shares will be calculated at share/asset ratio of roughly `1e18 : 1000`, resulting in the user getting 100x shares than expected, or occurring a loss of ~99%. 99% of their funds will actually go towards other liquidity providers in a sort of a donation.

## Impact
Loss of funds

## Code Snippet
https://github.com/sherlock-audit/2023-12-arcadia/blob/main/lending-v2/src/Tranche.sol#L303C2-L308C6

## Tool used

Manual Review

## Recommendation
If the tranche has minted shares, only allow deposits if the `totalAssets` are above a certain threshold (e.g. 1e8)

**Comment by spacegliderrrr** [comment]
Escalate
Although chance of this happening is low, there will be multiple lending pools and given enough time, chances of this happening are feasible. Since likelihood is low, but impact is high, I believe it should be marked as Medium

**Comment by sherlock-admin2** [comment]
> Escalate
> Although chance of this happening is low, there will be multiple lending pools and given enough time, chances of this happening are feasible. Since likelihood is low, but impact is high, I believe it should be marked as Medium 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Thomas-Smets** [comment]
The chance that the amount of bad debt is just big enough to leave a dust amount bigger than 0, but smaller than VAS is already neglectable.

But even if this would happen, the pool would always be paused after such a big default event.
And as we said in the earlier comment this is easily resolved by donating an amount to bring the liquidity again above VAS.

So there is already a mitigation in place: donateToTranche().

**Comment by nevillehuang** [comment]
Agree with sponsors comments, in addition that the original issue does not present a scenario where a possible dust amount is reached.

**Comment by Czar102** [comment]
@spacegliderrrr any response?

**Comment by xtazy888** [comment]
@Czar102 hey, as I said imo the probability of such event occurring is not low enough to invalidate this issue and M should be justified. Saying that the pool will be paused and funds will be donated is not enforced in any way by the code. After such event the pool will not be paused by default, therefore any user could lose their money.

**Comment by Czar102** [comment]
@nevillehuang @Thomas-Smets is the documentation suggesting any such plans for pausing and donating?

**Comment by Thomas-Smets** [comment]
This example starts with a pool with 1e18 shares (-> before the bad debt the pool had more than 1e18 assets).
Next there is a default event where there is only 10 gwei left, or a default of 99.99999999999999% of the pool.

While not stated explicitly in the documents, I think it is quite obvious the pool will be paused after a loss of 99.99999999999999%.

Again a loss where there is just a dust amount left in a tranche is not possible under normal conditions, if it happens it means something very big went wrong in the protocol in the first place.

**Comment by Czar102** [comment]
Thank you @Thomas-Smets for elaboration.

Looking at this issue again, it seems to me that there will be no loss of funds – the ratio will be different, but aside from that, there will be no loss in terms of the assets except for several wei.

@nevillehuang @Thomas-Smets @spacegliderrrr @xtazy888 Am I misunderstanding something?

**Comment by Thomas-Smets** [comment]
No indeed, there will be no direct loss of funds.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2023-12-arcadia-judging/issues/66/#issuecomment-1969623961): rejected
